In [1]:
import numpy as np

# Функция для вычисления евклидова расстояния между двумя точками
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2)**2))

# Функция для нахождения двух ближайших кластеров в списке кластеров
def find_closest_clusters(clusters):
    min_dist = float('inf')
    closest_clusters = None
    for i in range(len(clusters)):
        for j in range(i+1, len(clusters)):
            dist = euclidean_distance(clusters[i].mean, clusters[j].mean)
            if dist < min_dist:
                min_dist = dist
                closest_clusters = (i, j)
    return closest_clusters

# Класс для представления кластера как списка точек и среднего значения
class Cluster:
    def __init__(self, points):
        self.points = points
        self.mean = np.mean(points, axis=0)


def agglomerative_clustering(X, n_clusters):
    # Инициализируем каждую точку как отдельный кластер
    clusters = [Cluster([x]) for x in X]
    for elem in clusters:
        print(elem.points)
    print('\n')
    # Повторяем до тех пор, пока не останется нужное число кластеров
    while len(clusters) > n_clusters:
        # Находим два ближайших кластера и объединяем их в один новый кластер
        i, j = find_closest_clusters(clusters)
        new_cluster = Cluster(np.concatenate([clusters[i].points, clusters[j].points]))

        # Удаляем старые кластера из списка и добавляем новый
        del clusters[j]
        del clusters[i]
        clusters.append(new_cluster)

        for elem in clusters:
            print(elem.points)
        print('\n')
    # Возвращаем список меток кластеров для каждой точки
    labels = np.zeros(len(X))
    for i, cluster in enumerate(clusters):
        for point in cluster.points:
            labels[np.where(X == point)[0]] = i
            
    return labels

In [2]:
data = list([[0, 3, 1, 0, 0],
             [4, 0, 1, 1, 1],
             [2, 24, 9, 1, 1],
             [1, 0, 4, 1, 0],
             [3, 0, 4, 0, 0]])
agglomerative_clustering(data, 1)

[[0, 3, 1, 0, 0]]
[[4, 0, 1, 1, 1]]
[[2, 24, 9, 1, 1]]
[[1, 0, 4, 1, 0]]
[[3, 0, 4, 0, 0]]


[[0, 3, 1, 0, 0]]
[[4, 0, 1, 1, 1]]
[[2, 24, 9, 1, 1]]
[[1 0 4 1 0]
 [3 0 4 0 0]]


[[0, 3, 1, 0, 0]]
[[2, 24, 9, 1, 1]]
[[4 0 1 1 1]
 [1 0 4 1 0]
 [3 0 4 0 0]]


[[2, 24, 9, 1, 1]]
[[0 3 1 0 0]
 [4 0 1 1 1]
 [1 0 4 1 0]
 [3 0 4 0 0]]


[[ 2 24  9  1  1]
 [ 0  3  1  0  0]
 [ 4  0  1  1  1]
 [ 1  0  4  1  0]
 [ 3  0  4  0  0]]




array([0., 0., 0., 0., 0.])